import java.util.Scanner;
public class Lab_01_1 {

	public static void main(String[] args) {
	Scanner input=new Scanner(System.in);
			System.out.print("a= ");
			double a=input.nextDouble();
			System.out.print("b= ");
			double b=input.nextDouble();
			System.out.print("c= ");
			double c=input.nextDouble();
			System.out.print("d= ");
			double d=input.nextDouble();
			double r=0;
			double F=1000;
			input.close();
			 System.out.println("number pi = " + Math.PI);
		        System.out.println("number e = " +Math.E);
		        System.out.println("a + b = " + r);
		        r = b - c;
		        System.out.println("b - c = " + r);
		        r = d / a;
		        System.out.println("d / a = " + r);
		        r = Math.sin(a);
		        System.out.println("sin(a) in radians = " + r);
		        r = Math.sin(Math.toDegrees(a));
		        System.out.println("sin(a) in degrees = " + r);
		        r = Math.cos(b);
		        System.out.println("cos(b) = " + r);
		        r = Math.tan(c);
		        System.out.println("tan(c) = " + r);
		        r = 1 / Math.tan(c);
		        System.out.println("cot(c) = " + r);
		        r = Math.toDegrees(Math.asin(a));
		        System.out.println("arcsin(a) in degrees = " + r);
		        r = Math.toDegrees(Math.acos(a));
		        System.out.println("arccos(a) in degrees = " + r);
		        r = Math.toDegrees(Math.atan(d/c));
		        System.out.println("arctan(d/c) in degrees = " + r);
		        r = Math.toDegrees(Math.atan2( d , c ));
		        System.out.println("atan2(d,c) = " + r);
		        r = Math.toDegrees(Math.atan((-d)/(-c)));
		        System.out.println("arctan((-d)/(-c)) in degrees = " + r);
		        r = Math.toDegrees(Math.atan2(-d,-c));
		        System.out.println("atan2((-d),(-c)) in degrees = " + r);
		        r =  Math.log(a) / Math.log(Math.E);
		        System.out.println("log(e)(a) = " + r);
		        r = Math.log(b) / Math.log(10);
		        System.out.println("log(10)(b) = " + r);
		        r = (Math.log(d) / Math.log(Math.E)  + 1);
		        System.out.println("log(e)(d) + 1 = " + r);
		        r = Math.exp(a);
		        System.out.println("e^(a) = " + r);
		        r = Math.exp(b) - 1;
		        System.out.println("e^(b) - 1 = " + r);
		        r = Math.sqrt(a);
		        System.out.println("sqrt(a) = " + r);
		        r = Math.cbrt(d);
		        System.out.println("sqrt(d) = " + r);
		        r = Math.sqrt( Math.pow(c,2) + Math.pow(d,2));
		        System.out.println("sqrt(c^2 + d^2) = " + r);
		        r = Math.signum(b);
		        System.out.println("Sign of b = " + r);
		        r = Math.abs(c);
		        System.out.println("|c| = " + r);
		        r = Math.abs(-c);
		        System.out.println("|-c| = " + r);
		        r = Math.ceil(-c);
		        System.out.println("ceil(-c) = " + r);
		        r = Math.floor(-c);
		        System.out.println("floor(-c) = " + r);
		        r = Math.round(-c);
		        System.out.println("round(-c) = " + r);
		        r = Math.pow(a,b);
		        System.out.println("a^b = " + r);
		        r = Math.sqrt(Math.pow((Math.abs(a-b)),2) +Math.pow(Math.abs(c-d),2));
		        System.out.println("distance between P1 and P2 = " +r);
		        r = Math.pow(a,2);
		        System.out.println("area of square of side a = " + r);
		        r = F / r;
		        System.out.println("Pressure on square = "+ r);
		        r = c * d;
		        System.out.println("area of rectangle of sides c and d = " + r);
		        r = F / r;
		        System.out.println("pressure on rectangle = " + r);
		        r = Math.PI * Math.pow(b,2);
		        System.out.println("area of circle of radius b = " + r);
		        r = F / r;
		        System.out.println("pressure on circle = " + r);
		        r = a*d /2;
		        System.out.println("area of right angle triangle of catheti a and d");
		        r = F / r;
		        System.out.println("pressure on triangle = " + r);
		        r = a +  273;
		        System.out.println("a in kelvin = " + r);
		        r = a * 1.8 +32;
		        System.out.println("a in fahrenheit = " + r);
		        r = Math.abs(b * Math.cos(c) * a * 9.81 * Math.sin(c));
		        System.out.println("work done = " + r);
			
	}

}
